source_project      =""
bucket_name         =""
source_dataset      =""
source_table        =""
destination_project =""
destination_dataset =""
destination_table   =""
service_account     =""
region              =""
zone                =""
dataflow_network    =""
dataflow_subnet     =""
temp_bucket         =""

